
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import customtkinter as ctk



window = ctk.CTk()
ctk.set_appearance_mode("Dark")
window.title("Login")


window.geometry("760x450")
window.configure(bg = "#03050B")


canvas = Canvas(
    window,
    bg = "#03050B",
    height = 450,
    width = 760,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=("src/img/login/image_1.png"))
image_1 = canvas.create_image(
    386.0,
    226.0,
    image=image_image_1
)

text_id=canvas.create_text(
    388.0,
    171.0,
    anchor="nw",
    text="Pozdrav,",
    fill="#FFFFFF",
    font=("Inter", 24 * -1)
)

canvas.create_rectangle(
    403,
    247.69999998807907,
    706,
    248.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    403,
    302.69999998807907,
    706,
    303.0,
    fill="#FFFFFF",
    outline="")

image_image_2 = PhotoImage(
    file=("src/img/TopFormLogoBeliMali2.png"))
image_2 = canvas.create_image(
    565.0,
    74.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=("src/img/login/entry_1.png"))
entry_bg_1 = canvas.create_image(
    555.5,
    292.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#1A1B20",
    fg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=403.0,
    y=281.0,
    width=303.0,
    height=20.0
)

def on_entry_click(event):
   if entry_1.get() == "Lozinka":
      entry_1.delete(0, END)
      entry_1.configure(foreground="white")
      entry_1.configure(show='•')

def on_focus_out(event):
   if entry_1.get() == "":
      entry_1.insert(0, "Lozinka")
      entry_1.configure(foreground="gray",show='')

entry_1.configure(foreground="gray")
entry_1.insert(0, "Lozinka")
entry_1.bind("<FocusIn>", on_entry_click)
entry_1.bind("<FocusOut>", on_focus_out)

entry_image_2 = PhotoImage(
    file=("src/img/login/entry_2.png"))
entry_bg_2 = canvas.create_image(
    554.5,
    236.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#1A1B20",
    fg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=403,
    y=225.0,
    width=303.0,
    height=20.0
)

def on_entry_click2(event):
   if entry_2.get() == "Korisničko ime":
      entry_2.delete(0, END)
      entry_2.configure(foreground="white")

def on_focus_out2(event):
   if entry_2.get() == "":
      entry_2.insert(0, "Korisničko ime")
      entry_2.configure(foreground="gray")
      

def funk(event):
    canvas.itemconfig(text_id, text="Pozdrav, "+str(entry_2.get()))

entry_2.configure(foreground="gray")
entry_2.insert(0, "Korisničko ime")
entry_2.bind("<FocusIn>", on_entry_click2)
entry_2.bind("<FocusOut>", on_focus_out2)
entry_2.bind("<KeyRelease>", funk)

    

button_image_1 = PhotoImage(
    file=("src/img/login/button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=475.0,
    y=351.0,
    width=160.0,
    height=35.0
)

button_image_2 = PhotoImage(
    file=("src/img/login/button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=513.0,
    y=396.0,
    width=80.0,
    height=15.0
)

def set_custom_tab_order(event):
    if event.widget == entry_2:
        entry_1.focus_set()
    elif event.widget == entry_1:
        entry_2.focus_set()
    else:
        entry_2.focus_set()
    return "break"

entry_1.bind("<Tab>", set_custom_tab_order)
entry_2.bind("<Tab>", set_custom_tab_order)

window.resizable(False, False)
window.mainloop()
