
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import customtkinter
import queries
from datetime import date
import helperFunctions



def start(window,user):
    window.title('Kreiraj nalog')
    global return_value
    return_value = 0

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 450,
        width = 760,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(file=("src/img/Signup/image_1.png"))
    
    image_1 = canvas.create_image(
        380.0,
        225.0,
        image=image_image_1
    )
    
    def vrati(window,text):
        global return_value
        return_value=text
        window.quit()
    
    def napraviNalog():
        usrname=username.get()
        imeIPrezime=name.get().split(" ")
        if(len(imeIPrezime)!=2):
            helperFunctions.pisi_eror("Polje ime i prezime mora da ima samo 2 argumenta")
            return
        ime=imeIPrezime[0]
        prezime=imeIPrezime[1]
        lozinka=password.get()
        uloga=0
        status_clanstva=1
        uplacen_paket=0
        datum_registracije=date.today().strftime("%Y-%m-%d")
        if(queries.napraviNalog(usrname,lozinka,ime,prezime,uloga,status_clanstva,uplacen_paket,datum_registracije)=="vecPostoji"):
            helperFunctions.pisi_eror("Nalog sa korisničkim imenom već postoje")
            
    def on_name_click(event):
        if name.get() == "Ime i Prezime":
            name.delete(0, END)
            name.configure(foreground="white")

    def on_name_out(event):
        if name.get() == "":
            name.insert(0, "Ime i Prezime")
            name.configure(foreground="gray",show='')
            
    def change_welcome_text(event):
        canvas.itemconfig(text_id, text="Dobrodošao/la, "+str((name.get().split(' '))[0]))
        
    
    def on_username_click(event):
        if username.get() == "Korisničko ime":
            username.delete(0, END)
            username.configure(foreground="white")

    def on_username_out(event):
        if username.get() == "":
            username.insert(0, "Korisničko ime")
            username.configure(foreground="gray",show='')
            
    def on_password_click(event):
        if password.get() == "Lozinka":
            password.delete(0, END)
            password.configure(foreground="white")
            password.configure(show='•')

    def on_password_out(event):
        if password.get() == "":
            password.insert(0, "Lozinka")
            password.configure(foreground="gray",show='')
    

    name_image = PhotoImage(
        file=("src/img/Signup/entry_1.png"))
    name_bg = canvas.create_image(
        197.5,
        220.0,
        image=name_image
    )
    name = Entry(
        bd=0,
        bg="#131419",
        fg="#000716",
        highlightthickness=0
    )
    name.place(
        x=46.0,
        y=209.0,
        width=303.0,
        height=20.0
    )
    name.configure(foreground="gray")
    name.insert(0, "Ime i Prezime")
    name.bind("<FocusIn>", on_name_click)
    name.bind("<FocusOut>", on_name_out)
    name.bind("<KeyRelease>",change_welcome_text)

    username_image = PhotoImage(
        file=("src/img/Signup/entry_2.png"))
    username_bg = canvas.create_image(
        197.5,
        264.0,
        image=username_image
    )
    username = Entry(
        bd=0,
        bg="#131419",
        fg="#000716",
        #highlightthickness=0
    )
    username.place(
        x=46.0,
        y=253.0,
        width=303.0,
        height=20.0
    )
    username.configure(foreground="gray")
    username.insert(0, "Korisničko ime")
    username.bind("<FocusIn>", on_username_click)
    username.bind("<FocusOut>", on_username_out)
    

    password_image = PhotoImage(
        file=("src/img/Signup/entry_3.png"))
    password_bg = canvas.create_image(
        197.5,
        304.0,
        image=password_image
    )
    password = Entry(
        bd=0,
        bg="#131419",
        fg="#000716",
        highlightthickness=0
    )
    password.place(
        x=46.0,
        y=293.0,
        width=303.0,
        height=20.0
    )
    
    password.configure(foreground="gray")
    password.insert(0, "Lozinka")
    password.bind("<FocusIn>", on_password_click)
    password.bind("<FocusOut>", on_password_out)
    password.bind("<Return>", napraviNalog)

    

    
    
    login_image = PhotoImage(
        file=("src/img/Signup/button_1.png"))
    login = Button(
        image=login_image,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: vrati(window,"login"),
        relief="flat"
    )
    login.place(
        x=163.0,
        y=379.0,
        width=76.0,
        height=15.0
    )

    canvas.create_rectangle(
        42.0,
        230.00000474521948,
        352.0,
        231.02317810058594,
        fill="#FFFFFF",
        outline="")

    canvas.create_rectangle(
        41.0,
        274.0,
        352.0000120401364,
        275.0,
        fill="#FFFFFF",
        outline="")

    canvas.create_rectangle(
        41.0,
        313.0,
        352.0000098859837,
        314.9935898159913,
        fill="#FFFFFF",
        outline="")

    text_id=canvas.create_text(
        39.0,
        172.0,
        anchor="nw",
        text="Dobrodošao/la, ",
        fill="#FFFFFF",
        font=("Inter SemiBold", 24 * -1)
    )

    def gostf():
        queries.cursor.execute("SELECT * FROM Korisnici")
        print(queries.cursor.fetchall())
    
    gost_image = PhotoImage(
        file=("src/img/Signup/button_2.png"))
    gost = Button(
        image=gost_image,
        borderwidth=0,
        highlightthickness=0,
        command=gostf,
        relief="flat"
    )
    gost.place(
        x=588.0,
        y=394.0,
        width=153.0,
        height=40.0
    )

    signup_image = PhotoImage(
        file=("src/img/Signup/button_3.png"))
    signup = Button(
        image=signup_image,
        borderwidth=0,
        highlightthickness=0,
        command=napraviNalog,
        relief="flat"
    )
    signup.place(
        x=121.0,
        y=337.0,
        width=160.0,
        height=35.0
    )

    image_image_2 = PhotoImage(file="src/img/TopFormLogoBeliMali2.png")
    image_2 = canvas.create_image(
        201.0,
        76.0,
        image=image_image_2
    )
    
    
    window.resizable(False, False)
    window.mainloop()

    return return_value
