
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import customtkinter

def start(window,user):
    window.title('Kreiraj nalog')
    global return_value
    return_value = 0

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 450,
        width = 760,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(file=("src/img/Signup/image_1.png"))
    
    image_1 = canvas.create_image(
        380.0,
        225.0,
        image=image_image_1
    )

    entry_image_1 = PhotoImage(
        file=("src/img/Signup/entry_1.png"))
    entry_bg_1 = canvas.create_image(
        197.5,
        220.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#131419",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=46.0,
        y=209.0,
        width=303.0,
        height=20.0
    )

    entry_image_2 = PhotoImage(
        file=("src/img/Signup/entry_2.png"))
    entry_bg_2 = canvas.create_image(
        197.5,
        264.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#131419",
        fg="#000716",
        #highlightthickness=0
    )
    entry_2.place(
        x=46.0,
        y=253.0,
        width=303.0,
        height=20.0
    )

    entry_image_3 = PhotoImage(
        file=("src/img/Signup/entry_3.png"))
    entry_bg_3 = canvas.create_image(
        197.5,
        304.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#131419",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=46.0,
        y=293.0,
        width=303.0,
        height=20.0
    )

    def vrati(window,text):
        global return_value
        return_value=text
        window.quit()

    login_image = PhotoImage(
        file=("src/img/Signup/login.png"))
    login = Button(
        image=login_image,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: vrati(window,"login"),
        relief="flat"
    )
    login.place(
        x=163.0,
        y=379.0,
        width=76.0,
        height=15.0
    )

    canvas.create_rectangle(
        42.0,
        230.00000474521948,
        352.0,
        231.02317810058594,
        fill="#FFFFFF",
        outline="")

    canvas.create_rectangle(
        41.0,
        274.0,
        352.0000120401364,
        275.0,
        fill="#FFFFFF",
        outline="")

    canvas.create_rectangle(
        41.0,
        313.0,
        352.0000098859837,
        314.9935898159913,
        fill="#FFFFFF",
        outline="")

    canvas.create_text(
        39.0,
        172.0,
        anchor="nw",
        text="Dobrodošao/la, ",
        fill="#FFFFFF",
        font=("Inter SemiBold", 16 * -1)
    )

    gost_image = PhotoImage(
        file=("src/img/Signup/button_2.png"))
    gost = Button(
        image=gost_image,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: vrati(window,"gost"),
        relief="flat"
    )
    gost.place(
        x=588.0,
        y=394.0,
        width=153.0,
        height=40.0
    )

    signup_image = PhotoImage(
        file=("src/img/Signup/button_3.png"))
    signup = Button(
        image=signup_image,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: vrati(window,"signup"),
        relief="flat"
    )
    signup.place(
        x=121.0,
        y=337.0,
        width=160.0,
        height=35.0
    )

    image_image_2 = PhotoImage(file="src/img/TopFormLogoBeliMali2.png")
    image_2 = canvas.create_image(
        201.0,
        76.0,
        image=image_image_2
    )
    window.resizable(False, False)
    window.mainloop()

    return return_value
